### ISSUE TITLE
Condition has length > 1 with R 4.2.1

### ISSUE THREAD

**Issue by dmenne** [rstudio/learnr#720]
learnr_0.10.5.9000, R 4.2.1.

Using your simple example for custom questions gives warning

```
Condition has length > 1 with R 4.2.1
```

in quiz.R, 

https://github.com/rstudio/learnr/blob/5cefff90953a168f241b96673852cbeaafebd4c1/R/quiz.R#L394-L397

because of the stricter type checking in R 4.2.1. See also my similar pull request https://github.com/rstudio/shiny/pull/3625.

It also does not work as expected, I have not try to track down if this is due to the warning.

```r
question_is_correct.always_correct <- function(question, value, ...) {
  return(learnr::mark_as(TRUE, message = NULL))
}

ques <- question(
  "Custom Method",
  answer("answer", correct = TRUE),
  answer("also marked as correct", correct = FALSE),
  type = c("always_correct", "learnr_checkbox")
)
ques
```

**Comment by gadenbuie** [comment]
Hi @dmenne, thanks for filing this issue! I just merged a fix in #721 and I also fixed the incorrect tutorial name in the `?question_methods` docs.

In the future, I highly recommend linking to other places you've asked related questions — I didn't see your comment in the discussions until just now. https://github.com/rstudio/learnr/discussions/719#discussioncomment-3317248

**Comment by dmenne** [comment]
Warning is gone now, but I believe it still does not work. The callback is never called.

![2022-08-04 10_45_45-How to use shiny](https://user-images.githubusercontent.com/506275/182805397-ad9d3fac-06fc-4a4e-a942-8d2b51615b59.png)

````
---
title: "How to use shiny"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r context="setup", include=FALSE}
library(learnr)

```

## Topic 1

### Using Shiny

```{r custom_class, echo = FALSE}
question_is_correct.always_correct <- function(question, value, ...) {
  return(learnr::mark_as(TRUE, message = NULL))
}

ques <- question(
  "Custom Method",
  answer("answer", correct = TRUE),
  answer("also marked as correct", correct = FALSE),
  type = c("always_correct", "learnr_checkbox")
)
ques
```

````
